### ISSUE TITLE
Objects using instancing loose their normal map on pressing P

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#330]
https://www.youtube.com/watch?v=BQdJVJsYULk (See at 2:00)

if you have a normal map on an object, then check 'use geometry instancing'  in materials, when you press P
the normal map goes away

**Comment by youle31** [comment]
maybe related to #320. Test file: https://drive.google.com/file/d/0B29hKf6-B52cZE5URlE5YUs4UU0/view?usp=sharing

**Comment by youle31** [comment]
Fixed in 0f8a297d7aed79b4895abcf2d8ceec848fdb0caf (panzergame commit)

**Comment by BluePrintRandom** [comment]
thanks, let me known when you have a win32 or win64 test build :)

**Comment by youle31** [comment]
test file: http://pasteall.org/blend/index.php?id=44633

**Comment by panzergame** [comment]
@youle31, @DCubix, @lordloki: The issue is caused by the fact that the GLSL function `mtex_bump_init_objspace` is using `gl_ModelViewMatrix` without apply the object matrix in case of GI. But even if i apply the GI object matrix it still doesn't work.

If someone have time to look at this, thanks in advance.

**Comment by youle31** [comment]
I don't understand geometry instancing, but there are some matrix that seem unused:

varinstinvlocaltoviewmat, varinstlocaltoviewmat, unless I made a mistake...

**Comment by youle31** [comment]
This seems related to BluePrintRandom file only. With a simple cube with a texture and a normal, GI renders like non GI. I don't know where the bug comes from...

**Comment by BluePrintRandom** [comment]
do you have multiple instances of the normal map textured cube?

maybe the first copy is correct and not subsequent copies?

**Comment by youle31** [comment]
@BluePrintRandom : http://pasteall.org/blend/index.php?id=44656

**Comment by BluePrintRandom** [comment]
in your file it works yes, in my file I can add a cube - unwrap it - and texture it with a normal map and it works fine, it's only that mesh that seems affected :|


(the kit was quite a bit of work)

**Comment by panzergame** [comment]
Fixed in 2eaa0c64c8e790b29daf92fe58b7874ce5f71cbc.
