### ISSUE TITLE
Pixel dimensions bugs

### ISSUE THREAD

**Issue by HG1-Public** [UPBGE/blender#560]
UPBGE still have some pixel dimensions bugs.
ge.render.getWindowWidth/Height(), offScreenWidth/Height and mouse position does not match up.
Only offScreenWidth/Height match up with bgl_RenderedTextureWidth/Height.

1. The offScreenWidth and offScreenHeight is always one pixel bigger.
2.  In the embedded player mouse position is minus one pixel off. Start at -1, -1 to 639, 479.
3. In the standalone player the mouse position don't match with the letterbox size like in the embedded player. Instead it will always use the whole windows size.

https://www.dropbox.com/s/qitnilcm6htcfww/_PixelBugUPBGE.blend?dl=1

**Comment by panzergame** [comment]
Indeed the managing of render area is not the same between blenderplayer and blender, when I discovered it while working on the off screen internal render (summer of 0.1.0) I tried to stabilize a bit the behaviour but didn't changed to much things because of incompatiblity issues with filters and mouse.

blender render in an area without the bar (framing setting) whereas blenderplayer renders in the full window area so that the 2d filter see the bars and the mouse position cover all the window.
I didn't remove this behaviour in blenderplayer, even if i found it very odd, because of the compatiblity of game using mouse position in python etc..., but at the end if the game developer use blender to make it's game it should produce the same in blenderplayer at the cost of the compatiblity.

What `offScreenWidth` ?

I will see for embedded mouse shift.

**Comment by panzergame** [comment]
I could not reproduce the pixel shift in blender.

**Comment by HG1-Public** [comment]
> What offScreenWidth ?

offScreenWidth [Property] --> filter0.offScreen.width

> I could not reproduce the pixel shift in blender.

Did you mean in Bender BGE? Or did you mean you cant reproduce the mouse position offset?

**Comment by panzergame** [comment]
>>> Did you mean in Bender BGE? Or did you mean you cant reproduce the mouse position offset?

I can't reproduce the mouse offset (-1) in blender embedded BGE.

**Comment by HG1-Public** [comment]
I have the mouse pixel offset in BGE and UPBGE.
https://www.dropbox.com/s/t6m4hpvih6cxuzs/_PixelBugBGE.blend?dl=0

BGE/UPBGE
Mouse Actuator--> cont.sensors["Mouse"].position
Mouse Python --> logic.mouse.position
![mouseoffsetbge_upbge](https://user-images.githubusercontent.com/18644197/29205309-540cd860-7e7c-11e7-8474-b49d2e8ae590.png)

UPBGE
Mouse Python new --> mouse[bge.events.MOUSEX].values[-1]
![mouseoffsetupbge](https://user-images.githubusercontent.com/18644197/29205313-551e6f66-7e7c-11e7-8c32-0f3ae6f3451b.png)

**Comment by panzergame** [comment]
![mouse_origin](https://user-images.githubusercontent.com/8046004/29212272-ebeaf8b2-7e9d-11e7-86b1-517427fbdded.png)

**Comment by HG1-Public** [comment]
You are on Windows or Linux?

**Comment by panzergame** [comment]
Linux, hmm, you think it's a issue in GHOST ?

**Comment by HG1-Public** [comment]
Maybe. I think it is a Windows or Microsoft mouse driver issue.
But at the time I am in holidays. So I can't test it on an other PC.

**Comment by panzergame** [comment]
@HG1-Public : I fixed the issue related to window width and heigh in master could you test to make sure it work for you please ?

@youle31, @AkiraSan1,  @DCubix : Could you each of you test on your windows to see if you get the same issue as @HG1-Public with the mouse position shifted of one pixel, please ?

**Comment by Akira1San** [comment]
tested, made a pic: http://pasteall.org/pic/show.php?id=117902

**Comment by youle31** [comment]
It's ok for me both in embedded and blenderplayer (bge.render.getWindowWidth()/height() are matching the size of the filter)

About mouse position, I don't really know. In blenderplayer, with a 640x480 window, I have 639 max for the mouse position on the right side of the screen. Maybe this is normal...

**Comment by HG1-Public** [comment]
@panzergame:  
The 1. issue offScreenWidth/Height difference to getWindowWidth()/Height() is solved. Also tested with some shades.
The 2. issue is not solved. I still get the same values back. But there is now a new issue.
If I use bge.render.setMousePosition(0, 0) the mouse will be set to 0, -1 and the Mouse is placed one pixel off from the border in x(0) and correctly on the edge in y (-1). Before the patch setMousePosition(0, 0) the mouse was set to 0, 0 and in both directions one pixel off from the border, in the embedded player.

@youle31:
640x480 window the max should be 639x479, because we are starting at 0, 0.
The original water_0.99_optimized.blend from Martins Upitis is working for me.

@Akira1San:
first picture is **not correct**.
second is correct.

Found a new issue.
4. logic.mouse.position returns a value between 0.0 and 0,99xxxx. Should be 0.0 to 1.0. Possible mouse look issue here. Because of set position. 

We need to check all changes against the mouse look actuator and mouse look script (both mouse sensor and Python mouse).

For testing in windows: 
In Windows 7 to 10 there are some known issues. The DPI and desktop scaling can cause issues, if they are not set to 100%.

**Comment by youle31** [comment]
in water demo, writing this WM_cursor_warp(m_win, winX + x + 1, winY + (winH - y - 2)); instead of WM_cursor_warp(m_win, winX + x + 1, winY + (winH - y - 1)); in KX_BlenderCanvas::SetPosition fixes the mouselook issue that I have in water demo, but maybe it creates issue for you? I didn't check for mouseactuator... but all the methods related to mouse position don't use the code in KX_BlenderCanvas?

**Comment by HG1-Public** [comment]
@panzergame:
Today I saw that you are have made a "ge_mouse" branch. 
All mouse look scripts (rotation due get/set offset) and also the mouse look actuator are broken with it. 

This are my values (PixelBugBGE.blend):
bge.render.getWindowWidth()/Height() = 777, 438
top left corner cont.sensors["Mouse"].position = -1, -1
bottom right corner cont.sensors["Mouse"].position = 775, 436 

Values from mouse look:
getWindowWidth:  930 576
setMousePosition:  465 288
sens.position:  464 287
difference:  -1 -1
Debug: KX_BlenderCanvas::ConvertMousePosition(...), 464, 287

**Comment by panzergame** [comment]
Could you test with new `ge_mouse` ?

**Comment by HG1-Public** [comment]
Compile bug in KX_BlenderCanvas.cpp.
```
-    WM_cursor_warp(m_win, winX + x + 1, winY + (winH - y - 1));
+    WM_cursor_warp(m_win, winX + x + 1, winY + (winMaxY - y - 1));
```

I tested with new ge_mouse.
1. Mouse position still -1 pixel off.
2. Mouselook using cont.sensors["Mouse"].position works in embedded and standalone player.
3. Mouselook using logic.mouse.position now works in embedded without pixel fault workaround (in script). 
But don't work in standalone player with or without pixel fault workaround (works in UPBGE 0.1.8).
4. Mouselook actuator now working in embedded and standalone player.

I can test it next week with other PC's. If this bug also on my other PC's, I will try to fix, if I find some spare time.

**Comment by panzergame** [comment]
@HG1-Public : Could you test again with ge_mouse branch ?

**Comment by HG1-Public** [comment]
I tested with ge_mouse branch.
1. Mouse position still -1 pixel off in embedded player (letterbox and extended)
2. Mouse position in X direction -1 pixel off in Standalone player.
3. MouseLook2.5x_1.blend continuous movement in embedded player. Depends on screen size.

I found a new bug in UPBGE V0.1.8, V0.1.9, V0.2.0. The examples are working in Blender 2.79.
If I start a mouse look script in the **standalone player** the mouse position is off. Seems that setting the mouse cursor is delayed. I always get a huge difference value which rotate the camera at startup. 
I need to replace the always sensor with a delay sensor with 4 frames delay to get it work (MouseLook2.5x_1.blend). Which does not work with the MouseLook2.5x_2.blend, because it use a mouse sensor instead.
https://www.dropbox.com/s/9vg8v83ux0ai19u/MouseLook2.5x_1.blend?dl=1
https://www.dropbox.com/s/63hatz3bo66b397/MouseLook2.5x_2.blend?dl=1

**Comment by panzergame** [comment]
1 and 2)

I tested with:
```python
bge.render.setMousePosition(0, 0)
```

And get the correct placement of mouse and correct read position. Did you tested in a other OS ?


3)
The script is incorrect for an odd size, you can even test it by faking the read mouse position:

```python
   +x = R.getWindowWidth()//2/R.getWindowWidth()-0.5
   -x = R.getWindowWidth()//2/R.getWindowWidth()-G.mouse.position[0]
   +y = R.getWindowHeight()//2/R.getWindowHeight()-0.5
   -y = R.getWindowHeight()//2/R.getWindowHeight()-G.mouse.position[1]
```

Because of the integer division you lost one pixel if the size is odd and then you always have a gap.

**Comment by HG1-Public** [comment]
> Did you tested in a other OS ?
No. I tested it only on two different PC's (my home PC GTX 460, office laptop Quadro FX 3700) both running Windows 7 64 bit. 
If I have some free time I will test it with an other PC with an Intel and AMD graphic card. Maybe I can it also test on Window 10 PC. 

> The script is incorrect for an odd size, you can even test it by faking the read mouse position:
> Because of the integer division you lost one pixel if the size is odd and then you always have a gap. Just > use / instead of //
I know that. This script was made for official blender up to 2.79 and UPBGE 0.2.0 releases. "//" will fix the pixel offset bug in this versions. I don't changed and saved it to work with the patched version.
The with your patch the the value is now scaled between 0.0 and 1.0 so this workaround is not necessary any more.
But after G.mouse.position = (0.5,0.5) the cursor position will return (0.49921754002571106, 0.4989561438560486) and so it will move on even resolutions (640, 480 standalone player) on my PC. I also can't easily store the returned value as offset value  to calculate the correct difference, because the first 4 frames will return incorrect values.
I updated MouseLook2.5x_1.blend link.

**Comment by HG1-Public** [comment]
I have tested it now on the Windows 7 PC with the Intel and the AMD graphic card and the Windows 10 laptop with Intel graphic card. On all PC's I have the same issue.

**Comment by youle31** [comment]
Hi, I did quick tests in last ge_mouse. I noticed a backward compatibility with desert level mouselook (the camera moves to the sky in ge_mouse. I don't know what is the right behaviour. The master one or the ge_mouse one). Else HG1 file worked in embedded for me.

I think we shouldn't touch to canvas code unless we are sure that it won't cause backward compatibility issues, and as it seems the behaviour changes according to OS or hardwares, I think it's a bit risky to touch to this code. I think in most case the fix can be done by the user in the .blend code.

For me, the most important issue is the letter box mismatch in blenderplayer, but here too, I don't really know if we can change the code (for backward compatibility reasons).
I have this issue with letterbox in eevee branch (some post process effects are distorted). I think we should find an "internal" fix for that but without changing the behaviour for the user.

I didn't really worked on this problem and I don't realize all what it involves but these are the ideas I have when I think about this issue...

**Comment by youle31** [comment]
At this commit: c57754f8046 , in HG1 file (first post file), I have this result: http://pasteall.org/pic/show.php?id=119503 when I move the mouse on top left of the screen in embedded

**Comment by HG1-Public** [comment]
I made an new patch, it includes all changes from panzergame and my modifications.
I don't know it it will work correct on Linux PC.
https://www.dropbox.com/s/4e0kmk0mugqj1hl/MouseAll2.diff?dl=1

**Comment by panzergame** [comment]
@HG1-Public : What are your modifications in the patch ? The offset ? If yes it match the recent offset used in ge_mouse (= no offset).

**Comment by HG1-Public** [comment]
@@ -153,18 +163,18 @@ void KX_BlenderCanvas::ConvertMousePosition(int x, int y, int &r_x, int &r_y, bo
 		y = _y;
 	}
 
-	r_x = x - m_area_rect.GetLeft() - 1;
-	r_y = -y + m_area_rect.GetTop() - 1;
+	r_x = x - m_area_rect.GetLeft();
+	r_y = -y + m_area_rect.GetTop();
 }
 
@@ -239,9 +242,9 @@ void KX_BlenderCanvas::SetMousePosition(int x, int y)
 {
 	int winX = m_area_rect.GetLeft();
 	int winY = m_area_rect.GetBottom();
-	int winH = m_area_rect.GetHeight();
+	int winMaxY = m_area_rect.GetMaxY();
 
-	WM_cursor_warp(m_win, winX + x + 1, winY + (winH - y - 1));
+	WM_cursor_warp(m_win, winX + x, winY + (winMaxY - y));
 }

revert pervious changes +1
@@ -168,7 +172,7 @@ void GPG_Canvas::SetMousePosition(int x, int y)
 		GHOST_TInt32 cx;
 		GHOST_TInt32 cy;
 		m_window->clientToScreen(gx, gy, cx, cy);
-		system->setCursorPosition(cx + 1, cy);
+		system->setCursorPosition(cx, cy);
 	}
 }

revert pervious change -1
 void GPG_Canvas::ConvertMousePosition(int x, int y, int &r_x, int &r_y, bool UNUSED(screen))
 {
-	m_window->screenToClient(x, y, r_x, r_y);
+	int _x;
+	int _y;
+	m_window->screenToClient(x, y, _x, _y);
+
+	r_x = _x;
+	r_y = _y;
 }
